#include <iostream>
using namespace std;

int main()
{
// INPUT AND OUTPUT

    // (>> extraction operator >> is used to read input from the user and store it in the variable age. >>)

    int age = 0, marks = 0;

    cout << "Enter your age: ";
    cin >> age;

    cout << "Enter your marks: ";
    cin >> marks;

    cout << "Your age is: " << age << endl;
    cout << "Your marks are: " << marks << endl;
    return 0;
}
